version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: memo-app
    volumes:
      - .:/go/src/memo-docker
    ports:
      - "80:8080"
    depends_on:
      - db
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  db:
    image: mysql:latest
    restart: always
    container_name: memo-app-db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memo_app
    hostname: db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - ./log/mysql:/var/log/mysql
      - ./sql:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"
# マイグレーションは一時的にこの方法でsql実行しているだけ
# 今後やりたいこと：migrate/migrateの使用とデータ永続化
