version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: memo-app
    volumes:
      - .:/go/src/memo-docker
    ports:
      - "80:8080"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.0
    restart: always
    container_name: memo-app-db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memo-app
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
